#!/bin/sh

# Run python 'cwwords.py' program to practice Morse Code

# set -x

PREFIX=${HOME}/local/deploy/cwwords
CFG_PREFIX=${HOME}/amateur-radio/cwwords

if [ "words" = "$1" ]; then
    ARG="-f ${CFG_PREFIX}/words.cfg"
elif [ "wordlist" = "$1" ]; then
    ARG="-f ${CFG_PREFIX}/wordlist.cfg"
elif [ "callsigns" = "$1" ]; then
    ARG="-f ${CFG_PREFIX}/callsigns.cfg"
elif [ "calllist" = "$1" ]; then
    ARG="-f ${CFG_PREFIX}/calllist.cfg"
elif [ "qsos" = "$1" ]; then
    ARG="-f ${CFG_PREFIX}/qsos.cfg"
elif [ "common" = "$1" ]; then
    ARG="-f ${CFG_PREFIX}/common.cfg"
elif [ "commonlist" = "$1" ]; then
    ARG="-f ${CFG_PREFIX}/commonlist.cfg"
elif [ "ninja" = "$1" ]; then
    ARG="-f ${CFG_PREFIX}/ninja.cfg"
else
    ARG="$@"
fi

${PREFIX}/venv/bin/python ${PREFIX}/cwwords.py ${ARG}

