#!/bin/sh


# The number of Koch characters to use
NUM_KOCH_CHARS=25

# Character speed in words per minute
WPM=20

# Farnsworth effective words per minute
# FARNSWORTH_WPM=3
FARNSWORTH_WPM=2

# CW tone frequency
FREQUENCY=600

# Total number of words
TOTAL_WORDS=20

# Minimum word length
MIN_WORD_LEN=3

# Maximum word length
MAX_WORD_LEN=8

./cwwords.py -k $NUM_KOCH_CHARS \
             -w $WPM \
             -n $FARNSWORTH_WPM \
             -f $FREQUENCY \
             -t $TOTAL_WORDS \
             -s $MIN_WORD_LEN \
             -m $MAX_WORD_LEN \
             -p
#             -r \

