#!/bin/sh


# The number of Koch characters to use
NUM_KOCH_CHARS=40

# Character speed in words per minute
WPM=20

# Farnsworth effective words per minute
FARNSWORTH_WPM=3
# FARNSWORTH_WPM=2

# CW tone frequency
FREQUENCY=600

# Total number of words
TOTAL_WORDS=20

# Minimum word length
MIN_WORD_LEN=3

# Maximum word length
MAX_WORD_LEN=5

VIRTUALENV="$HOME/devel/python/cwwords/venv/bin/activate"

source $VIRTUALENV

CMD="./cwwords.py --koch-chars $NUM_KOCH_CHARS \
                  --wpm $WPM \
                  --farns-wpm $FARNSWORTH_WPM \
                  --freq $FREQUENCY \
                  --tot-words $TOTAL_WORDS \
                  --min-word-len $MIN_WORD_LEN \
                  --max-word-len $MAX_WORD_LEN \
                  --play \
                  --random"

echo $CMD

$CMD
